;
; AssemblerApplication1.asm
;
; Created: 10/18/2022 5:25:29 PM
; Author : Paul
;


; Replace with your application code
.ORG 0
LDI R16, HIGH(RAMEND)
OUT SPH, R16
LDI R16, LOW(RAMEND)
OUT SPL, R16

LDI R17, 0X04
LDI R18, 0
CBI DDRD, 4; PORTD BIT 4 CONFIGURED AS INPUT (LEFT BUTTON ON CIRCUIT PLAYGROUND BOARD)
SBI PORTD, 4; SET PULL-UP RESISTOR FOR INPUT PORT PIN 4 (COVERED IN CHAPTER 4)
SBI DDRC, 6
OUT PORTC, R18 ; sound?

START:  SBIC PIND, 4; SEE IF LEFT BUTTON IS PUSHED (PORTD BIT 4 PUSHED IS A 1)
		EOR R18,R17
		OUT PORTC, R18 
		RJMP Start
Delay:	LDI R21, -50
		OUT TCNT0, R21
		LDI R21, 0X01
Again:	OUT TCCR0B, R21
		RJMP Again
		LDI R21,0x00
		SBIS TIFR0, TOV0
		OUT TCCR0B,R21
		LDI R21, (1<<TOV0)
		OUT TIFR0, R21
		RJMP START  ; GO BACK TO START OF LOOP TO SEE STATUS OF LEFT BUTTON AND REPEAT
